[package]
name = "space"
version = "0.1.0"
authors = ["Mischa Aster Alff <mischa.alff@gmail.com>"]

[dependencies]
piston2d-graphics = "0.4.1"
piston2d-opengl_graphics = "0.6.0"
piston_window = "0.15.0"
